
#include "reserv/core/inc/rsrv_decision.h"
#include <string.h>

/*=============================================================================================================*/

static const struct _DESC_ARRAY
{
    TreservMCUDiagVector    diag_vector;  
    TRoles                  decs_role; 
} mcu_desc_array[] =
{ 
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_SLAVE,  RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_MASTER, RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_SLAVE  },
  
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_SLAVE,  RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_MASTER, RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },

  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_SLAVE,  RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_MASTER, RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_SLAVE  },
  
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_SLAVE,  RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },
  { {RESERV_TREESTATE_CHECKED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_MASTER, RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },

  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_SLAVE,  RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_MASTER, RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_SLAVE,  RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_PRES, RESERV_ROLES_MASTER, RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_SLAVE  },

  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_SLAVE,  RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_MASTER, RSRV_DNEPR_MAIN_SLOT},    RESERV_ROLES_MASTER },
  
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_SLAVE,  RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_UNKNOWN,RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_MASTER },
  { {RESERV_TREESTATE_DAMAGED, RSRV_DNEPR_PRESSIGNAL_NONE, RESERV_ROLES_MASTER, RSRV_DNEPR_RESERVE_SLOT}, RESERV_ROLES_MASTER },
};

/*=============================================================================================================*/

/*=============================================================================================================*/
/*!  \brief 

     \sa 
*/
/*=============================================================================================================*/
TRoles rsrv_make_mcu_descision 
(
  TreservMCUDiagVector  *input_vector
)
{
   int   i;
   
   for ( i = 0; i < (sizeof mcu_desc_array / sizeof mcu_desc_array[0]); i++ ) {
       if ( memcmp( input_vector, &mcu_desc_array[i].diag_vector, sizeof mcu_desc_array[i].diag_vector) == 0 ) {  
           break; 
       }
   }
   
   if ( i == (sizeof mcu_desc_array / sizeof mcu_desc_array[0]) )
   {  return RESERV_ROLES_SLAVE; }
  
   return mcu_desc_array[i].decs_role;
}
