/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Mon Feb 24 12:56:49 2014. */

#include "SlotEEPROM_Optional.pb.h"

const SlotEEPROM_Message_PCB_Type SlotEEPROM_Message_type_default = SlotEEPROM_Message_PCB_Type_ACTIVE;


const pb_field_t SlotEEPROM_Message_fields[5] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, SlotEEPROM_Message, serial, serial, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, SlotEEPROM_Message, description, serial, 0),
    PB_FIELD2(  3, ENUM    , REQUIRED, STATIC  , OTHER, SlotEEPROM_Message, type, description, &SlotEEPROM_Message_type_default),
    PB_FIELD2(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, SlotEEPROM_Message, passive_message, type, &SlotEEPROM_Message_Passive_fields),
    PB_LAST_FIELD
};

const pb_field_t SlotEEPROM_Message_Passive_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, SlotEEPROM_Message_Passive, image, image, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(SlotEEPROM_Message, passive_message) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SlotEEPROM_Message_SlotEEPROM_Message_Passive)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(SlotEEPROM_Message, passive_message) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SlotEEPROM_Message_SlotEEPROM_Message_Passive)
#endif


