/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Mon Feb 24 12:56:49 2014. */

#ifndef _PB_SLOTEEPROM_OPTIONAL_PB_H_
#define _PB_SLOTEEPROM_OPTIONAL_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SlotEEPROM_Message_PCB_Type {
    SlotEEPROM_Message_PCB_Type_ACTIVE = 0,
    SlotEEPROM_Message_PCB_Type_PASSIVE = 1,
    SlotEEPROM_Message_PCB_Type_FAN = 2
} SlotEEPROM_Message_PCB_Type;

/* Struct definitions */
typedef struct _SlotEEPROM_Message_Passive {
    pb_callback_t image;
} SlotEEPROM_Message_Passive;

typedef struct _SlotEEPROM_Message {
    pb_callback_t serial;
    pb_callback_t description;
    SlotEEPROM_Message_PCB_Type type;
    bool has_passive_message;
    SlotEEPROM_Message_Passive passive_message;
} SlotEEPROM_Message;

/* Default values for struct fields */
extern const SlotEEPROM_Message_PCB_Type SlotEEPROM_Message_type_default;

/* Field tags (for use in manual encoding/decoding) */
#define SlotEEPROM_Message_Passive_image_tag     1
#define SlotEEPROM_Message_serial_tag            1
#define SlotEEPROM_Message_description_tag       2
#define SlotEEPROM_Message_type_tag              3
#define SlotEEPROM_Message_passive_message_tag   4

/* Struct field encoding specification for nanopb */
extern const pb_field_t SlotEEPROM_Message_fields[5];
extern const pb_field_t SlotEEPROM_Message_Passive_fields[2];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
