/*!
\file PSMI_Registers.h
\brief PSMI registers and coefficients.
\details Supported devices:
	\li Emerson DS850DC-3x (power supply unit).
\author Daniel Leonov, <a href="mailto:leonov@t8.ru">leonov@t8.ru</a>
\date 16.04.2012
*/

#ifndef __PSMI_REGISTERS_H
#define __PSMI_REGISTERS_H

#define __DS650DC_3

#define PSMI_TEMP_SENSOR_BASE 0x00
#define PSMI_TEMP_SENSOR(ch) ( PSMI_TEMP_SENSOR_BASE + (ch-1) )
#define PSMI_TEMP_SENSOR_NUMBER 4
#define PSMI_TEMP_SENSOR_COEFFICIENT ( 1/64. )

#define PSMI_FAN_SPEED_SENSOR_BASE 0x20
#define PSMI_FAN_SPEED_SENSOR(ch) ( PSMI_FAN_SPEED_SENSOR_BASE + (ch-1) )
#define PSMI_FAN_SPEED_SENSOR_NUMBER 4
#define PSMI_FAN_SPEED_SENSOR_COEFFICIENT ( 100. ) //?

#define PSMI_FAN_SPEED_CONTROL_BASE 0x24
#define PSMI_FAN_SPEED_CONTROL(ch) ( PSMI_FAN_SPEED_CONTROL_BASE + (ch-1) )
#define PSMI_FAN_SPEED_CONTROL_NUMBER 4
#define PSMI_FAN_SPEED_CONTROL_COEFFICIENT ( 100. ) //?

#define PSMI_VOUT_SENSOR_BASE 0x28
#define PSMI_VOUT_SENSOR(ch) ( PSMI_VOUT_SENSOR_BASE + (ch-1) )
#define PSMI_VOUT_SENSOR_NUMBER 10
#define PSMI_VOUT_SENSOR_COEFFICIENT ( 1/256. )

#define PSMI_VIN_SENSOR_BASE 0x32
#define PSMI_VIN_SENSOR(ch) ( PSMI_VIN_SENSOR_BASE + (ch-1) )
#define PSMI_VIN_SENSOR_NUMBER 1
#define PSMI_VIN_SENSOR_COEFFICIENT ( 1/128. )

#define PSMI_IOUT_SENSOR_BASE 0x33
#define PSMI_IOUT_SENSOR(ch) ( PSMI_IOUT_SENSOR_BASE + (ch-1) )
#define PSMI_IOUT_SENSOR_NUMBER 10
#define PSMI_IOUT_SENSOR_COEFFICIENT ( 1/64. )

#define PSMI_IIN_SENSOR_BASE 0x3D
#define PSMI_IIN_SENSOR(ch) ( PSMI_IIN_SENSOR_BASE + (ch-1) )
#define PSMI_IIN_SENSOR_NUMBER 1
#define PSMI_IIN_SENSOR_COEFFICIENT ( 1/32. )

#define PSMI_IOUT_PEAK_SENSOR_BASE 0x53
#define PSMI_IOUT_PEAK_SENSOR(ch) ( PSMI_IOUT_PEAK_SENSOR_BASE + (ch-1) )
#define PSMI_IOUT_PEAK_SENSOR_NUMBER 10
#define PSMI_IOUT_PEAK_SENSOR_COEFFICIENT ( 1/64. )

#define PSMI_IIN_PEAK_SENSOR_BASE 0x5D
#define PSMI_IIN_PEAK_SENSOR(ch) ( PSMI_IIN_PEAK_SENSOR_BASE + (ch-1) )
#define PSMI_IIN_PEAK_SENSOR_NUMBER 1
#define PSMI_IIN_PEAK_SENSOR_COEFFICIENT ( 1/64. )

#define PSMI_1_OUTPUT_POWER_LIMIT	0xA5
#define PSMI_2_OUTPUT_POWER_LIMIT	0xA6
#define PSMI_3_OUTPUT_POWER_LIMIT	0xA7

#define	PSMI_STATUS_REGISTER    0x62
#define	PSMI_SHUTDOWN_EVENTS    0x5E
#define	PSMI_CONTROLS_REGISTER  0x62
#define	PSMI_WARNING_REGISTER_1 0x5F
#define	PSMI_WARNING_REGISTER_2 0x60
#define	PSMI_WARNING_REGISTER_3 0x61

#endif
